name: Squatober Message

# Runs at 7am in October
# on:
#   schedule:
#    - cron: "0 7 26 9 *"

jobs:
  build:
    # Our instance will use the latest available version of Ubuntu.
    runs-on: ubuntu-latest

    # These steps are run in the same order as are defined.
    steps:
      # actions checkout and python are pre-built actions
      # that abstract commonly used tasks.
      - uses: actions/checkout@v3

      # The python action will set us a Python 3.8 (64-bit) instance.
      - name: Setting up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.8"
          architecture: "x64"

      # Use PIP to install the dependencies and then run the script.
      - name: Running Script
        # But first we read the WEBHOOK secret and create an
        # environment variable with the same name.
        env:
          EMAIL_USER: ${{ secrets.EMAIL_USER }}  # Load secrets securely
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
          PHONE_NUMBERS: ${{ secrets.PHONE_NUMBERS }}
        run:
          python main.py
